### ISSUE TITLE
move LapH_EigSys to hiskp-lqcd repo

### ISSUE THREAD

**Issue by kostrzewa** [chelmes/LapH_EigSys#7]
@chelmes @urbach @pittlerf @martin-ueding @matfischer

This should be moved to hiskp-lqcd such that we can maintain it for the future and add some much-needed improvements, especially for checking that vectors are actually eigenvectors.

**Comment by martin-ueding** [comment]
I agree. Christopher has to do that though, in *Settings* and then *Transfer Ownership* to `HISKP-LQCD`.

**Comment by chelmes** [comment]
Hi, there is already a fork of ths repo in HISKP-LQCD. In order to transfer ownership this has to go first, otherwise I would have to rename it.

**Comment by kostrzewa** [comment]
@chelmes Thanks for taking a look, I've deleted the fork.

**Comment by chelmes** [comment]
Done.

**Comment by kostrzewa** [comment]
Thanks @chelmes
